workspace/config/routes.rb
Rails.application.routes.draw do
  get 'notes/new' => 'notes#new'
  post 'notes' => 'notes#create'
  root 'home#top'
  get 'r2' => 'home#r2'
  get 'r3' => 'home#r3'
  get '/notes/:id' => 'notes#show',as:'note'
  get '/notes/:id/edit' => 'notes#edit',as:'edit_note'
  patch '/notes/:id' => 'notes#update', as: 'update_note'
  delete '/notes/:id' => 'notes#destroy', as:'destroy_note'

end

workspace/app/models/note.rb
class Note < ActiveRecord::Base
end

workspace/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

workspace/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  def r2
    @notes = Note.all
  end
  def r3
     @notes = Note.all
  end
end

workspace/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
  end
  def create
   @note = Note.new
   @note.title = params[:title]
   @note.content = params[:content]
   @note.category = params[:category]
   @note.save
   redirect_to note_path(@note.id)
  end
  def show
    @note = Note.find(params[:id])
  end
  def edit
    @note = Note.find(params[:id])
  end
  def update
    @note = Note.find(params[:id])
    @note.title = params[:title]
    @note.content = params[:content]
    @note.save
    redirect_to note_path(@note.id)
  end
  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    if @note.category == "3" then
      redirect_to r3_path
    else
      redirect_to r2_path
    end
  end
end

workspace/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/app/helpers/home_helper.rb
module HomeHelper
end

workspace/app/helpers/notes_helper.rb
module NotesHelper
end

workspace/app/views/home/r2.html.erb
  <h1>電脳工場MF R2.0</h1>

<h2>投稿の一覧</h2>
<ul class="notes">
  <% @notes.each do |note| %>
    <% if note.category == "2" %>
      <li>
        <p>タイトル</p>
        <span class="content">
          <%= link_to note.title, note_path(note.id) %>
        </span>
      </li>
    <%end%>
  <%end%>
</ul>

workspace/app/views/home/r3.html.erb
  <h1>電脳工場MF R3.0</h1>

<h2>投稿の一覧</h2>
<ul class="notes">
  <% @notes.each do |note| %>
    <% if note.category == "3" %>
      <li>
        <p>タイトル</p>
        <span class="content">
          <%= link_to note.title, note_path(note.id) %>
        </span>
      </li>
    <%end%>
  <%end%>
</ul>

workspace/app/views/home/top.html.erb
  <h1>ようこそ電脳工場ー開発資料集へ！</h1>

workspace/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Factory-ONE</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
 <header class="navbar">
  <div class="container">
    <div id="logo">Factory-ONE</div>
    <ul class="header-right">
      <li><%= link_to "Top", root_path %></li>
      <li><%= link_to "R2.0", r2_path %></li>
      <li><%= link_to "R3.0", r3_path %></li>
      <li><%= link_to "New", notes_new_path %></li>
    </ul>
  </div>
</header>
<body>
<div class="container">
<%= yield %>
</div>
 <div class="container">
  <footer class="footer">
    <div class="small">
      &copy; 2016 EXcorporation.All rights reserved.
    </div>
  </footer>
</div>
</body>
</html>

workspace/app/views/notes/edit.html.erb
<h1>投稿を編集する</h1>
<%= form_tag update_note_path(@note.id),method:'patch' do %>
  <%= text_field_tag :title , @note.title, class: "form-control title-field"%>
  <%= text_area_tag :content, @note.content, class: "form-control content-content-field" %>
  <%= submit_tag "保存", class: "btn primary-btn"%>
<% end %>

workspace/app/views/notes/new.html.erb
<h1>新規投稿する</h1>
<%= form_tag notes_path do %>
カテゴリー
<select name="category" class="form-control styled-select">
    <option value="3">R3.0</option>
    <option value="2">R2.0</option>
</select>
タイトル
<input type="text" name="title" class="form-control title-field">
内容
<textarea name="content" class="form-control content-field"></textarea>
<input type="submit" value="投稿する" class="btn primary-btn">
<% end %>

workspace/app/views/notes/show.html.erb
<h2>タイトル</h2>
<p><%=@note.title%></p>
<h2>内容</h2>
<p><%=@note.content%></p>

<%= link_to "編集", edit_note_path(@note.id), class: "btn edit-btn" %>
<%= link_to "削除", destroy_note_path(@note.id), method: "delete", class: "btn destroy-btn", "data-confirm" => "本当に削除しますか？" %>